apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: neowaytc
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/m2tx/deploy-argocd.git'
    targetRevision: main
    path: my-app
  destination:
    server: https://kubernetes.default.svc
    namespace: neowaytc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
